// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type ChartData struct {
	CHARTDATE string  `json:"CHART_DATE"`
	OPEN      float64 `json:"OPEN"`
	HIGH      float64 `json:"HIGH"`
	LOW       float64 `json:"LOW"`
	CLOSE     float64 `json:"CLOSE"`
	VALUE     float64 `json:"VALUE"`
}

type CompanyMatch struct {
	CmpyId string `json:"cmpyId"`
	CmpyNm string `json:"cmpyNm"`
	Symbol string `json:"symbol"`
	EtfYn  string `json:"etfYn"`
}

type PhisixQuote struct {
	Name   string `json:"name"`
	Symbol string `json:"symbol"`
	AsOf   string `json:"as_of"`
}
