// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/ph-commons/pse-edge-pp-cli/internal/cli"
	"github.com/ph-commons/pse-edge-pp-cli/internal/client"
	"github.com/ph-commons/pse-edge-pp-cli/internal/cliutil"
	"github.com/ph-commons/pse-edge-pp-cli/internal/config"
	"github.com/ph-commons/pse-edge-pp-cli/internal/learn"
	"github.com/ph-commons/pse-edge-pp-cli/internal/mcp/bound"
	"github.com/ph-commons/pse-edge-pp-cli/internal/mcp/cobratree"
	"github.com/ph-commons/pse-edge-pp-cli/internal/store"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("companies_directory",
			mcplib.WithDescription("One page of the full listed-company directory (name, symbol, cmpy_id, security_id). Optional: page (default: 1)."),
			mcplib.WithNumber("page", mcplib.Description("Directory page number (about 50 companies per page)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/companyDirectory/search.ax", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "page", WireName: "pageNo", Location: "query", Default: "1"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("companies_lookup",
			mcplib.WithDescription("Search companies by name or symbol prefix (first 20 alphabetical matches only — use exact-match filtering). Required: query. Returns array of CompanyMatch."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Company name or ticker symbol prefix")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/autoComplete/searchCompanyNameSymbol.ax", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "query", WireName: "term", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("companies_profile",
			mcplib.WithDescription("Company profile page: sector, subsector, incorporation, auditor. Required: company-id. Optional: security-id."),
			mcplib.WithNumber("company-id", mcplib.Required(), mcplib.Description("PSE Edge company ID (from resolve or the directory)")),
			mcplib.WithNumber("security-id", mcplib.Description("Security ID for multi-class listings (from the directory)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/companyInformation/form.do", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "company-id", WireName: "cmpy_id", Location: "query"}, {PublicName: "security-id", WireName: "security_id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("disclosures_document",
			mcplib.WithDescription("Full disclosure document content as server-rendered HTML (use this, never the broken downloadFile.do PDF path). Required: file-id."),
			mcplib.WithNumber("file-id", mcplib.Required(), mcplib.Description("Document file ID from the disclosure viewer")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/downloadHtml.do", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "file-id", WireName: "file_id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("disclosures_search",
			mcplib.WithDescription("Search disclosures by company, template, and date range (server-side; the keyword parameter is IGNORED upstream — use the filings command for client-side keyword filtering). Upstream expects a form-urlencoded body, not JSON. Optional: company-id, keyword, template (plus 2 more)."),
			mcplib.WithString("company-id", mcplib.Description("PSE Edge company ID (empty searches all companies)")),
			mcplib.WithString("keyword", mcplib.Description("Free-text keyword filter")),
			mcplib.WithString("template", mcplib.Description("Disclosure template name filter (e.g. Quarterly Report)")),
			mcplib.WithString("from-date", mcplib.Description("Range start, MM-DD-YYYY")),
			mcplib.WithString("to-date", mcplib.Description("Range end, MM-DD-YYYY")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/announcements/search.ax", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "company-id", WireName: "companyId", Location: "body"}, {PublicName: "keyword", WireName: "keyword", Location: "body"}, {PublicName: "template", WireName: "tmplNm", Location: "body"}, {PublicName: "from-date", WireName: "fromDate", Location: "body"}, {PublicName: "to-date", WireName: "toDate", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("disclosures_view",
			mcplib.WithDescription("Disclosure viewer wrapper for one filing. Required: edge-no."),
			mcplib.WithString("edge-no", mcplib.Required(), mcplib.Description("Disclosure hash from search results")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/openDiscViewer.do", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "edge-no", WireName: "edge_no", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("financials_report",
			mcplib.WithDescription("Balance-sheet and income-statement summary tables for a company (server-rendered HTML; authoritative when the PDF download is broken). Required: company-id."),
			mcplib.WithNumber("company-id", mcplib.Required(), mcplib.Description("PSE Edge company ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/companyPage/financial_reports_view.do", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "company-id", WireName: "cmpy_id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("market_composite",
			mcplib.WithDescription("Composite/sector page: PSEi and sector indices, market summary (volume, value, trades, advances/declines/unchanged), embedded daily PSEi series since 2021. HTML-entity-encoded JSON uses single-encoded &quot; — decode before parsing. Page is ~1.5MB."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://frames.pse.com.ph/compositeSector", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("prices_history",
			mcplib.WithDescription("Daily OHLC and value-traded history for one security (first-party JSON). Required: company-id, security-id, start-date, end-date. Returns the new ChartData."),
			mcplib.WithNumber("company-id", mcplib.Required(), mcplib.Description("PSE Edge company ID")),
			mcplib.WithNumber("security-id", mcplib.Required(), mcplib.Description("Security ID (from the directory; required for correct series)")),
			mcplib.WithString("start-date", mcplib.Required(), mcplib.Description("Range start, MM-DD-YYYY")),
			mcplib.WithString("end-date", mcplib.Required(), mcplib.Description("Range end, MM-DD-YYYY")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/common/DisclosureCht.ax", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "company-id", WireName: "cmpy_id", Location: "body"}, {PublicName: "security-id", WireName: "security_id", Location: "body"}, {PublicName: "start-date", WireName: "startDate", Location: "body"}, {PublicName: "end-date", WireName: "endDate", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("prices_snapshot",
			mcplib.WithDescription("Current-session stock data page: last price, change, OHLC, volume, value, market cap. Required: company-id. Optional: security-id."),
			mcplib.WithNumber("company-id", mcplib.Required(), mcplib.Description("PSE Edge company ID")),
			mcplib.WithNumber("security-id", mcplib.Description("Security ID for multi-class listings (GTCAP-class companies need this)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/companyPage/stockData.do", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "company-id", WireName: "cmpy_id", Location: "query"}, {PublicName: "security-id", WireName: "security_id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("quotes_get",
			mcplib.WithDescription("EOD quote for one ticker: close, percent change, volume. as_of is a synthetic midnight stamp — it carries no trade-time information; derive the trading date from the session calendar. Required: symbol. Returns the PhisixQuote."),
			mcplib.WithString("symbol", mcplib.Required(), mcplib.Description("Ticker symbol, exact match (e.g. AT, GTCAP)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "https://phisix-api3.appspot.com/stocks/{symbol}.json", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "symbol", WireName: "symbol", Location: "path"}}, []string{"symbol"}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='companies'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
	Default    string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcpToolError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'pse-edge-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'pse-edge-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			return mcplib.NewToolResultText(string(out)), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultText(method, data, pageConfig, mcpCursor), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcplib.NewToolResultText(bound.EndpointResponse(method, data))
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcplib.NewToolResultText(bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	}))
}

func newMCPClient() (*client.Client, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, err
	}
	return newMCPClientFromConfig(cfg), nil
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(cfg *config.Config) *client.Client {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

type mcpStoreStatusKind string

const (
	mcpStoreStatusEmpty mcpStoreStatusKind = "empty"
	mcpStoreStatusReady mcpStoreStatusKind = "ready"
)

func openMCPReadOnlyStore(path string) (*store.Store, *mcplib.CallToolResult) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, mcplib.NewToolResultError(mcpMissingStoreMessage(path))
		}
		return nil, mcplib.NewToolResultError(fmt.Sprintf("checking local data store %s: %v", path, err))
	}
	db, err := store.OpenReadOnly(path)
	if err != nil {
		return nil, mcplib.NewToolResultError(fmt.Sprintf("opening local data store %s: %v. Run pse-edge-pp-cli sync to refresh the store, or use live endpoint MCP tools for unsynced data.", path, err))
	}
	return db, nil
}

func mcpMissingStoreMessage(path string) string {
	return fmt.Sprintf("No local data store found at %s. Run pse-edge-pp-cli sync before using MCP search/sql, or use live endpoint MCP tools for unsynced data.", path)
}

func mcpStoreStatus(db *store.Store) (mcpStoreStatusKind, error) {
	status, err := db.Status()
	if err != nil {
		return "", err
	}
	if len(status) == 0 {
		return mcpStoreStatusEmpty, nil
	}
	return mcpStoreStatusReady, nil
}

func mcpEmptyStoreNextStep() string {
	return "Run pse-edge-pp-cli sync to populate the local SQLite store before using MCP search/sql."
}

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSearchEnvelope(results, storeStatus))
}

func mcpSearchEnvelope(results []json.RawMessage, storeStatus mcpStoreStatusKind) map[string]any {
	if results == nil {
		results = []json.RawMessage{}
	}
	out := map[string]any{
		"count":        len(results),
		"results":      results,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if len(results) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "No local search matches. Try a broader query, a lower-specificity FTS expression, or sync again if data may be stale."
		}
	}
	return out
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	rows, err := db.DB().QueryContext(ctx, query)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSQLEnvelope(results, cols, storeStatus))
}

func mcpSQLEnvelope(rows []map[string]any, columns []string, storeStatus mcpStoreStatusKind) map[string]any {
	if rows == nil {
		rows = []map[string]any{}
	}
	out := map[string]any{
		"count":        len(rows),
		"columns":      columns,
		"rows":         rows,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if len(rows) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "The read-only SQL query returned no rows. Check resource_type filters, json_extract paths, or run sync again if data may be stale."
		}
	}
	return out
}

func mcpSQLQueryError(err error) string {
	msg := err.Error()
	if strings.Contains(strings.ToLower(msg), "no such table") {
		return fmt.Sprintf("query failed: %v. Synced records live in resources(resource_type, id, data), not one SQL table per resource. Filter by resource_type, for example resource_type='companies', and read JSON fields with json_extract(data,'$.field').", err)
	}
	return fmt.Sprintf("query failed: %v", err)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "pse-edge",
		"description": "Agent-native Philippine Stock Exchange CLI — quotes, filings, and a local price history no free API serves.",
		"archetype":   "generic",
		"tool_count":  11,
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion pse-edge-pp-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"resources": []map[string]any{
			{
				"name":        "companies",
				"description": "Listed-company registry: directory, lookup, and profiles",
				"endpoints":   []string{"directory", "lookup", "profile"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "disclosures",
				"description": "Corporate disclosures: search, view, and read filing documents",
				"endpoints":   []string{"document", "search", "view"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "financials",
				"description": "17-Q/17-A financial summary tables (annual + quarterly)",
				"endpoints":   []string{"report"},
			},
			{
				"name":        "market",
				"description": "Market-wide data: PSEi, sector indices, breadth, totals",
				"endpoints":   []string{"composite"},
			},
			{
				"name":        "prices",
				"description": "Per-ticker prices: current session snapshot and daily history",
				"endpoints":   []string{"history", "snapshot"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "quotes",
				"description": "Fast EOD quotes via the community phisix JSON mirror (unofficial redeploy — may vanish",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Local history query", "command": "history", "description": "Query daily OHLC/value history for any ticker or the PSEi from the local store — data no free PSE API serves.", "rationale": "Exists only because sync builds a SQLite series from the DisclosureCht.ax endpoint plus the embedded 2021-to-present PSEi series.", "via": "mcp-command-mirror"},
			{"name": "Drift / relative strength", "command": "drift", "description": "Percent change over a window, absolute and versus the PSEi over the same sessions, with 52-week band position.", "rationale": "Requires joining per-ticker prices with index snapshots over calendar-aligned sessions — only possible in the local store.", "via": "mcp-command-mirror"},
			{"name": "Session state", "command": "session", "description": "Philippine trading-calendar verdict: trading day or not, pre/post-close gate, last completed trading date.", "rationale": "No endpoint exists; computed locally from the PH trading calendar and the 16:00 Asia/Manila close gate.", "via": "mcp-command-mirror"},
			{"name": "Freshness audit", "command": "stale", "description": "Per-ticker last-synced trading date versus the last completed trading day, with in-series gaps listed.", "rationale": "Joins local price series against the computed trading calendar — a completeness check no source offers.", "via": "mcp-command-mirror"},
			{"name": "Filing-deadline tracker", "command": "deadlines", "description": "Computed 17-Q/17-A due dates per SRC Rule 68 45/105-day windows, joined to local disclosures: filed, pending, or overdue.", "rationale": "The due date exists nowhere in the API; it is computed and joined to the local disclosures index.", "via": "mcp-command-mirror"},
			{"name": "Breadth trend", "command": "breadth", "description": "Advance/decline/unchanged and value-traded trend over time from local index snapshots.", "rationale": "The market page offers a single snapshot; the trend exists only in the accumulated local series.", "via": "mcp-command-mirror"},
			{"name": "Local movers", "command": "movers", "description": "Ranked gainers and losers across the synced universe for a window, with universe size and as-of stated.", "rationale": "No PSE endpoint ranks movers; only possible over the local store's cross-ticker series.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Local history query", "insight": "Exists only because sync builds a SQLite series from the DisclosureCht.ax endpoint plus the embedded 2021-to-present PSEi series."},
			{"topic": "Drift / relative strength", "insight": "Requires joining per-ticker prices with index snapshots over calendar-aligned sessions — only possible in the local store."},
			{"topic": "Session state", "insight": "No endpoint exists; computed locally from the PH trading calendar and the 16:00 Asia/Manila close gate."},
			{"topic": "Freshness audit", "insight": "Joins local price series against the computed trading calendar — a completeness check no source offers."},
			{"topic": "Filing-deadline tracker", "insight": "The due date exists nowhere in the API; it is computed and joined to the local disclosures index."},
			{"topic": "Breadth trend", "insight": "The market page offers a single snapshot; the trend exists only in the accumulated local series."},
			{"topic": "Local movers", "insight": "No PSE endpoint ranks movers; only possible over the local store's cross-ticker series."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
