// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCompaniesProfileCmd(flags *rootFlags) *cobra.Command {
	var flagCmpyId string
	var flagSecurityId string

	cmd := &cobra.Command{
		Use:         "profile",
		Short:       "Company profile page: sector, subsector, incorporation, auditor",
		Example:     "  pse-edge-pp-cli companies profile --company-id 633 --security-id 628",
		Annotations: map[string]string{"pp:endpoint": "companies.profile", "pp:method": "GET", "pp:path": "/companyInformation/form.do", "mcp:read-only": "true", "pp:happy-args": "--company-id=633;--security-id=628"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("company-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "company-id")
			}
			path := "/companyInformation/form.do"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			htmlRequestParams := map[string]string{}
			if flagCmpyId != "" {
				htmlRequestParams["cmpy_id"] = formatCLIParamValue(flagCmpyId)
			}
			if flagSecurityId != "" {
				htmlRequestParams["security_id"] = formatCLIParamValue(flagSecurityId)
			}
			params := map[string]string{}
			if flagCmpyId != "" {
				params["cmpy_id"] = formatCLIParamValue(flagCmpyId)
			}
			if flagSecurityId != "" {
				params["security_id"] = formatCLIParamValue(flagSecurityId)
			}
			data, prov, err := resolveReadWithStrategyResponsePathAndJSONGuard(cmd.Context(), c, flags, "auto", "companies", false, path, params, nil, "", false, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if !flags.dryRun {
				data, err = extractHTMLResponse(data, htmlExtractionOptions{
					Mode:           "page",
					BaseURL:        htmlExtractionRequestURL(c.BaseURL, path, htmlRequestParams),
					LinkPrefixes:   []string{},
					Limit:          0,
					ScriptSelector: "script#__NEXT_DATA__",
					JSONPath:       "",
				})
				if err != nil {
					return err
				}
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagCmpyId, "company-id", "", "PSE Edge company ID (from resolve or the directory)")
	cmd.Flags().StringVar(&flagSecurityId, "security-id", "", "Security ID for multi-class listings (from the directory)")

	return cmd
}
