// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCompaniesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "companies",
		Short:       "Listed-company registry: directory, lookup, and profiles",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCompaniesDirectoryCmd(flags))
	cmd.AddCommand(newCompaniesLookupCmd(flags))
	cmd.AddCommand(newCompaniesProfileCmd(flags))
	return cmd
}
