// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"net"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
)

func TestParseDeliverSink_WebhookScheme(t *testing.T) {
	cases := []struct {
		name  string
		spec  string
		valid bool
	}{
		{"stdout default", "", true},
		{"stdout explicit", "stdout", true},
		{"file", "file:/tmp/x.json", true},
		{"webhook http", "webhook:http://example.com/hook", true},
		{"webhook https", "webhook:https://example.com/hook", true},
		{"webhook ftp rejected", "webhook:ftp://example.com/hook", false},
		{"webhook no scheme rejected", "webhook:169.254.169.254", false},
		{"webhook empty target", "webhook:", false},
		{"unknown scheme", "carrier:pigeon", false},
		{"no colon", "file", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseDeliverSink(tc.spec)
			if tc.valid && err != nil {
				t.Fatalf("ParseDeliverSink(%q) unexpected error: %v", tc.spec, err)
			}
			if !tc.valid && err == nil {
				t.Fatalf("ParseDeliverSink(%q) expected error, got nil", tc.spec)
			}
		})
	}
}

func TestIsBlockedDestinationIP(t *testing.T) {
	blocked := []string{
		"0.0.0.0",
		"10.0.0.1",
		"100.64.0.1",      // CGNAT
		"127.0.0.1",       // loopback
		"169.254.169.254", // cloud metadata
		"172.16.0.1",
		"192.0.2.1",   // TEST-NET-1
		"192.88.99.1", // 6to4 anycast
		"192.168.1.1",
		"198.18.0.1", // benchmarking
		"224.0.0.1",  // multicast
		"240.0.0.1",  // reserved
		"255.255.255.255",
		"::",                 // unspecified
		"::1",                // loopback
		"::127.0.0.1",        // deprecated IPv4-compatible (embeds loopback)
		"2002:7f00:1::",      // 6to4 embedding 127.0.0.1
		"64:ff9b::a00:1",     // NAT64 embedding 10.0.0.1
		"fc00::1",            // ULA
		"fe80::1",            // link-local
		"ff02::1",            // multicast
		"::ffff:127.0.0.1",   // IPv4-mapped loopback
		"::ffff:192.168.0.1", // IPv4-mapped RFC1918
		"::ffff:0:a00:1",     // deprecated IPv4-translated embedding 10.0.0.1
	}
	for _, s := range blocked {
		ip := net.ParseIP(s)
		if ip == nil {
			t.Fatalf("bad test IP literal %q", s)
		}
		if !isBlockedDestinationIP(ip) {
			t.Errorf("isBlockedDestinationIP(%q) = false, want true", s)
		}
	}

	allowed := []string{
		"8.8.8.8",
		"1.1.1.1",
		"2606:4700:4700::1111",
		"::ffff:8.8.8.8", // IPv4-mapped PUBLIC must not be blocked
	}
	for _, s := range allowed {
		ip := net.ParseIP(s)
		if ip == nil {
			t.Fatalf("bad test IP literal %q", s)
		}
		if isBlockedDestinationIP(ip) {
			t.Errorf("isBlockedDestinationIP(%q) = true, want false", s)
		}
	}

	// Fail-closed: unparseable net.IP values are blocked.
	if !isBlockedDestinationIP(nil) {
		t.Error("isBlockedDestinationIP(nil) = false, want true (fail-closed)")
	}
	if !isBlockedDestinationIP(net.IP{}) {
		t.Error("isBlockedDestinationIP(empty) = false, want true (fail-closed)")
	}
}

func TestCheckWebhookDestination(t *testing.T) {
	blocked := []string{
		"http://127.0.0.1:8080/admin",
		"http://10.0.0.1/",
		"http://169.254.169.254/latest/meta-data",
		"http://192.168.1.1:9000/hook",
	}
	for _, u := range blocked {
		if err := checkWebhookDestination(u); err == nil {
			t.Errorf("checkWebhookDestination(%q) = nil, want block error", u)
		}
	}

	// Hostname that resolves to loopback (localhost in /etc/hosts).
	if err := checkWebhookDestination("http://localhost:8080/hook"); err == nil {
		t.Error("checkWebhookDestination(http://localhost) = nil, want block error")
	}

	// Literal public IP passes.
	if err := checkWebhookDestination("http://8.8.8.8/hook"); err != nil {
		t.Errorf("checkWebhookDestination(http://8.8.8.8) unexpected error: %v", err)
	}

	// Host without a host.
	if err := checkWebhookDestination("http:///hook"); err == nil {
		t.Error("checkWebhookDestination(http:///hook) = nil, want error")
	}

	// Hex-form IPv4: deterministic — if the resolver interprets it the
	// destination is 127.0.0.1 (blocked); if it cannot resolve it, the
	// fail-closed DNS error blocks delivery. Either way an error.
	if err := checkWebhookDestination("http://0x7f000001/"); err == nil {
		t.Error("checkWebhookDestination(http://0x7f000001) = nil, want block or fail-closed error")
	}

	// Trailing-dot hostname: lookup fails on most resolvers -> fail-closed.
	if err := checkWebhookDestination("http://169.254.169.254./"); err == nil {
		t.Error("checkWebhookDestination(trailing-dot metadata) = nil, want fail-closed error")
	}
}

func TestWebhookClientRedirectPolicy(t *testing.T) {
	req, err := http.NewRequest(http.MethodPost, "http://169.254.169.254/latest/meta-data", strings.NewReader("x"))
	if err != nil {
		t.Fatal(err)
	}
	if err := webhookClient(false).CheckRedirect(req, nil); err == nil {
		t.Error("webhookClient(false) redirect to metadata = nil, want block error")
	}
	if err := webhookClient(true).CheckRedirect(req, nil); err != nil {
		t.Errorf("webhookClient(true) redirect to metadata unexpected error: %v", err)
	}
}

func TestDeliverWebhookAllowPrivateProceeds(t *testing.T) {
	// Deterministic opt-in path: a loopback httptest server is a blocked
	// destination by default, so only AllowPrivate=true should reach it.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNoContent)
	}))
	defer srv.Close()

	// Guard on (default): loopback destination must be refused.
	sink := DeliverSink{Scheme: "webhook", Target: srv.URL}
	err := Deliver(sink, []byte("{}"), true)
	if err == nil {
		t.Error("Deliver(webhook, loopback, guard on) = nil, want block error")
	}

	// Guard off (AllowPrivate): proceeds and reaches the server.
	sink.AllowPrivate = true
	if err := Deliver(sink, []byte("{}"), true); err != nil {
		t.Errorf("Deliver(webhook, loopback, AllowPrivate) unexpected error: %v", err)
	}
}

func TestDeliverWebhookRedirectRevalidated(t *testing.T) {
	// Both servers are loopback, so with the guard on the initial
	// destination check refuses before any hop. The redirect-hop
	// re-validation itself is pinned directly in TestWebhookClientRedirectPolicy;
	// this test covers the AllowPrivate opt-in path through a real
	// httptest redirect chain.
	var received atomic.Bool
	serverB := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		received.Store(true)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer serverB.Close()
	serverA := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, serverB.URL, http.StatusFound)
	}))
	defer serverA.Close()

	// Guard on: refused at the initial loopback destination.
	if err := Deliver(DeliverSink{Scheme: "webhook", Target: serverA.URL}, []byte("{}"), true); err == nil {
		t.Error("Deliver(redirect chain, guard on) = nil, want block error")
	}
	if received.Load() {
		t.Fatal("server B reached while guard was on")
	}

	// AllowPrivate: initial check passes and the redirect hop is allowed.
	if err := Deliver(DeliverSink{Scheme: "webhook", Target: serverA.URL, AllowPrivate: true}, []byte("{}"), true); err != nil {
		t.Fatalf("Deliver(redirect chain, AllowPrivate) unexpected error: %v", err)
	}
	if !received.Load() {
		t.Error("redirect hop not followed under AllowPrivate")
	}
}
