// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPricesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "prices",
		Short:       "Per-ticker prices: current session snapshot and daily history",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPricesHistoryCmd(flags))
	cmd.AddCommand(newPricesSnapshotCmd(flags))
	return cmd
}
