// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"testing"

	"github.com/spf13/cobra"
)

// TestApplyProfileToFlags_DoesNotOverlayDeliveryFlags pins that the
// per-invocation delivery switches (--deliver and the webhook SSRF
// opt-out, issue #25) are never overlaid from a saved profile: a
// profile that captured them while testing a local webhook must not
// silently carry guard-off state into later --profile runs.
func TestApplyProfileToFlags_DoesNotOverlayDeliveryFlags(t *testing.T) {
	cmd := &cobra.Command{Use: "root"}
	cmd.PersistentFlags().String("deliver", "", "deliver sink")
	cmd.PersistentFlags().Bool("deliver-webhook-allow-private", false, "ssrf opt-out")
	cmd.PersistentFlags().String("data-source", "auto", "data source")
	// cobra merges persistent flags into c.Flags() during ParseFlags;
	// mirror that so Lookup finds them (as it does at runtime in
	// PersistentPreRunE).
	cmd.Flags().AddFlagSet(cmd.PersistentFlags())

	profile := &Profile{Values: map[string]string{
		"deliver":                       "webhook:http://10.0.0.1/hook",
		"deliver-webhook-allow-private": "true",
		"data-source":                   "live", // non-reserved must still apply
	}}
	if err := ApplyProfileToFlags(cmd, profile); err != nil {
		t.Fatalf("ApplyProfileToFlags: %v", err)
	}
	if got, _ := cmd.PersistentFlags().GetString("deliver"); got != "" {
		t.Errorf("--deliver overlaid from profile: got %q, want empty", got)
	}
	if got, _ := cmd.PersistentFlags().GetBool("deliver-webhook-allow-private"); got {
		t.Error("--deliver-webhook-allow-private overlaid from profile, want false")
	}
	if got, _ := cmd.PersistentFlags().GetString("data-source"); got != "live" {
		t.Errorf("non-reserved flag --data-source not applied: got %q, want live", got)
	}
}

// TestProfileSaveSkipMapSuperset pins the invariant documented in
// profile.go: profileSaveSkipFlags must remain a superset of
// reservedProfileFlags, so a saved profile can never carry a value that
// ApplyProfileToFlags would silently refuse.
func TestProfileSaveSkipMapSuperset(t *testing.T) {
	for name := range reservedProfileFlags {
		if !profileSaveSkipFlags[name] {
			t.Errorf("profileSaveSkipFlags is not a superset of reservedProfileFlags: missing %q", name)
		}
	}
}
