// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Hand patch: resolveVersion for non-release builds (see .printing-press-patches/).

package cli

import (
	"fmt"
	"runtime/debug"
	"strings"

	"github.com/spf13/cobra"
)

// version is the printed CLI's version. Goreleaser overrides it via ldflags
// (-X …version={{ .Version }}). When left at the default, resolveVersion
// fills in the Go module pseudo-version or VCS revision so local installs
// are not stuck on "0.0.0-dev".
var version = "0.0.0-dev"

func init() {
	version = resolveVersion(version)
}

// Version returns the resolved CLI/MCP version string (no leading "v").
func Version() string {
	return version
}

// resolveVersion prefers an explicit ldflags value, then module build info,
// then embedded VCS settings, then the default.
func resolveVersion(ldflag string) string {
	if v := normalizeVersion(ldflag); v != "" && v != "0.0.0-dev" {
		return v
	}
	if bi, ok := debug.ReadBuildInfo(); ok {
		if v := normalizeVersion(bi.Main.Version); v != "" && v != "(devel)" {
			return v
		}
		var rev string
		modified := false
		for _, s := range bi.Settings {
			switch s.Key {
			case "vcs.revision":
				rev = s.Value
			case "vcs.modified":
				modified = s.Value == "true"
			}
		}
		if rev != "" {
			if len(rev) > 7 {
				rev = rev[:7]
			}
			if modified {
				return rev + "-dirty"
			}
			return rev
		}
	}
	return "0.0.0-dev"
}

// normalizeVersion strips a leading "v" so goreleaser (0.1.2) and module
// versions (v0.1.2) print the same way.
func normalizeVersion(v string) string {
	v = strings.TrimSpace(v)
	return strings.TrimPrefix(v, "v")
}

// newVersionCmd prints the CLI name and version. Shared by the HTTP and device
// generators so both printed-CLI shapes carry an identical version command.
func newVersionCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("%s %s\n", cmd.Root().Name(), version)
		},
	}
}
